kind: pipeline
type: docker
name: default

steps:
  
- 
    name: push  
    image: plugins/docker
    settings:
        dockerfile: Dockerfile
        repo: hilaolu/maddy
        username:
            from_secret: docker_username
        password:
            from_secret: docker_password
